### ISSUE TITLE
ng-strictdi is throwing error

### ISSUE THREAD

**Issue by Alphatiger** [pregiotek/ion-floating-menu#13]
ng-strictdi is throwing error
 error    Error: [$injector:strictdi] http://errors.angularjs.org/1.4.3/$injector/strictdi?p0=function(%24scope)
    at Error (native)
    at http://10.0.0.3:8100/js/ionic.bundle.min.js:40:416
    at Function.eb.$$annotate (http://10.0.0.3:8100/js/ionic.bundle.min.js:220:55)
    at Object.e [as invoke](http://10.0.0.3:8100/js/ionic.bundle.min.js:72:498)
    at P.instance (http://10.0.0.3:8100/js/ionic.bundle.min.js:114:122)
    at S (http://10.0.0.3:8100/js/ionic.bundle.min.js:95:199)
    at g (http://10.0.0.3:8100/js/ionic.bundle.min.js:88:384)
    at S (http://10.0.0.3:8100/js/ionic.bundle.min.js:95:498)
    at g (http://10.0.0.3:8100/js/ionic.bundle.min.js:88:384)
    at http://10.0.0.3:8100/js/ionic.bundle.min.js:87:444, <ion-nav-view name="menuContent" class="view-container" nav-view-transition="android">

I am having a side menu and my index.html is as follows
<body ng-app="app" ng-strict-di>
<ion-pane>

```
<ion-nav-bar class="bar-assertive">

    <ion-nav-back-button class="button-clear">
        <i class="ion-arrow-left-c" style="font-size: 25px"></i>
    </ion-nav-back-button>

</ion-nav-bar>
<ion-nav-view></ion-nav-view>
```

</ion-pane>

I have implemented the button it in one of template as mentioned in the docs,

If i remove ng-strictdi it is working fine

**Comment by Alphatiger** [comment]
In the script [] brackets are missing once i modified it is in compliance with  ng-strictdi
